# Generated by Django 2.2.3 on 2019-07-15 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trello.GroupModel'),
        ),
    ]
