# Generated by Django 2.2.3 on 2019-07-16 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0002_auto_20190715_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trello.GroupModel'),
        ),
    ]
