# Generated by Django 2.2.3 on 2019-07-16 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0003_auto_20190716_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmodel',
            options={'verbose_name': 'Group'},
        ),
    ]
